import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Map from '../comps/Map'
import {Header, Image, H2, H3, H4, Box, Container, List} from '../styles/global'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Translink - Expo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <Header>
          <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/TransLink_%28Vancouver%29_Logo.svg/1280px-TransLink_%28Vancouver%29_Logo.svg.png"></Image>
          <H2>Metro Vancouver&apos;s Transportation Network</H2>
        </Header>
        <Container width="90vw" display="flex" flexWrap="wrap" margin="90px 0 20px 0">
            <Box>
              <H3>The Expo Line is the oldest line of the SkyTrain rapid transit system in the Metro Vancouver region of British Columbia, Canada. The line is owned and operated by BC Rapid Transit Company, a subsidiary of TransLink, and links the cities of Vancouver, Burnaby, New Westminster and Surrey.</H3>
            </Box>
          
            <Box>
              <H3>Expo Line Information</H3>
              <Container>
                <List>Opened on December 11, 1985</List>
                <List>24 stations</List>
                <List>36 km line length</List>
                <List>148,000 daily riders</List>
              </Container>
            </Box>
        </Container>
       <Map/>
       <Container width="100vw" display="flex" justCont="center" padding="20px" bgColor="white" margin="30px 0 0 0">
              <H4>© 2023 TransLink, all rights reserved to Ana Arango 🤪</H4>
        </Container>
      </main>
    </div>
  )
}
